import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'bis';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.pos': 'POS',
    'nav.inventory': 'Inventory',
    'nav.utang': 'Utang',
    'nav.customers': 'Customers',
    'nav.navigation': 'Navigation',
    'nav.description.dashboard': 'Overview & Analytics',
    'nav.description.pos': 'Point of Sale System',
    'nav.description.inventory': 'Stock Management',
    'nav.description.utang': 'Credit Tracking',
    'nav.description.customers': 'Customer Database',
    
    // Dashboard
    'dashboard.todaysSales': "Today's Sales",
    'dashboard.totalSales': 'Total',
    'dashboard.totalUtang': 'Total Utang',
    'dashboard.monthlyUtang': 'Monthly',
    'dashboard.lowStockItems': 'Low Stock Items',
    'dashboard.needRestocking': 'Need restocking',
    'dashboard.customers': 'Customers',
    'dashboard.registeredCustomers': 'Registered customers',
    'dashboard.lowStockAlert': 'Low Stock Alert',
    'dashboard.itemsRequiringAttention': 'Items requiring immediate attention',
    'dashboard.allProductsWellStocked': 'All products are well stocked! 🎉',
    'dashboard.recentUnpaidUtang': 'Recent Unpaid Utang',
    'dashboard.latestCreditTransactions': 'Latest credit transactions',
    'dashboard.noUnpaidUtang': 'No unpaid utang records! 💰',
    'dashboard.left': 'left',
    'dashboard.min': 'Min',
    
    // POS System
    'pos.products': 'Products',
    'pos.cart': 'Cart',
    'pos.cartEmpty': 'Cart is empty',
    'pos.total': 'Total',
    'pos.checkout': 'Checkout',
    'pos.paymentMethod': 'Payment Method',
    'pos.cash': 'Cash',
    'pos.utang': 'Utang (Credit)',
    'pos.partialPayment': 'Partial Payment',
    'pos.customer': 'Customer',
    'pos.selectCustomer': 'Select customer',
    'pos.amountPaid': 'Amount Paid',
    'pos.change': 'Change',
    'pos.utangAmount': 'Utang Amount',
    'pos.processTransaction': 'Process Transaction',
    'pos.stock': 'Stock',
    'pos.outOfStock': 'Out of Stock',
    'pos.outOfStockDesc': 'is out of stock!',
    'pos.insufficientStock': 'Insufficient Stock',
    'pos.onlyAvailable': 'Only',
    'pos.available': 'available!',
    'pos.emptyCart': 'Empty Cart',
    'pos.emptyCartDesc': 'Please add items to cart before processing transaction.',
    'pos.insufficientPayment': 'Insufficient Payment',
    'pos.insufficientPaymentDesc': 'Payment amount is less than the required amount.',
    'pos.customerRequired': 'Customer Required',
    'pos.customerRequiredDesc': 'Please select a customer for utang transactions.',
    'pos.transactionCompleted': 'Transaction Completed',
    'pos.saleProcessed': 'Sale of ₱{amount} processed successfully!',
    
    // Inventory Management
    'inventory.addProduct': 'Add Product',
    'inventory.addNewProduct': 'Add New Product',
    'inventory.productName': 'Product Name',
    'inventory.category': 'Category',
    'inventory.price': 'Price',
    'inventory.stock': 'Stock',
    'inventory.minStock': 'Minimum Stock',
    'inventory.barcode': 'Barcode',
    'inventory.supplier': 'Supplier',
    'inventory.cancel': 'Cancel',
    'inventory.edit': 'Edit',
    'inventory.editProduct': 'Edit Product',
    'inventory.updateProduct': 'Update Product',
    'inventory.lowStockAlert': 'Low Stock Alert',
    'inventory.items': 'items',
    'inventory.searchProducts': 'Search products...',
    'inventory.products': 'Products',
    'inventory.currentStock': 'Current Stock',
    'inventory.noProductsFound': 'No products found matching your search.',
    'inventory.invalidInput': 'Invalid Input',
    'inventory.fillRequiredFields': 'Please fill in all required fields with valid values.',
    'inventory.productAdded': 'Product Added',
    'inventory.addedToInventory': 'has been added to inventory.',
    'inventory.productUpdated': 'Product Updated',
    'inventory.hasBeenUpdated': 'has been updated.',
    'inventory.productDeleted': 'Product Deleted',
    'inventory.removedFromInventory': 'has been removed from inventory.',
    'inventory.enterProductName': 'Enter product name',
    'inventory.enterCategory': 'Enter category',
    'inventory.enterBarcode': 'Enter barcode',
    'inventory.enterSupplier': 'Enter supplier name',
    
    // Utang Management
    'utang.utangManagement': 'Utang Management',
    'utang.trackAndManage': 'Track and manage customer debt records',
    'utang.totalUnpaidUtang': 'Total Unpaid Utang',
    'utang.all': 'All',
    'utang.unpaid': 'Unpaid',
    'utang.partial': 'Partial',
    'utang.paid': 'Paid',
    'utang.latest': 'Latest',
    'utang.transaction': 'transaction',
    'utang.transactions': 'transactions',
    'utang.allItemsPurchased': 'All Items Purchased',
    'utang.item': 'ITEM',
    'utang.qtyPrice': 'QTY × PRICE = TOTAL',
    'utang.totalAmount': 'Total Amount',
    'utang.balance': 'Balance',
    'utang.addPayment': 'Add Payment',
    'utang.paymentHistory': 'Payment History',
    'utang.noUtangRecords': 'No utang records found for the selected filter.',
    'utang.remainingBalance': 'Remaining Balance',
    'utang.paymentAmount': 'Payment Amount',
    'utang.note': 'Note (Optional)',
    'utang.addNoteForPayment': 'Add a note for this payment',
    'utang.recordPayment': 'Record Payment',
    'utang.invalidAmount': 'Invalid Amount',
    'utang.enterValidAmount': 'Please enter a valid payment amount.',
    'utang.overpayment': 'Overpayment',
    'utang.exceedsBalance': 'Payment amount exceeds remaining balance of P{amount}.',
    'utang.paymentRecorded': 'Payment Recorded',
    'utang.paymentOf': 'Payment of P{amount} has been recorded.',
    
    // Customer Management
    'customer.addCustomer': 'Add Customer',
    'customer.addNewCustomer': 'Add New Customer',
    'customer.customerName': 'Customer Name',
    'customer.phoneNumber': 'Phone Number',
    'customer.totalCustomers': 'Total Customers',
    'customer.withUtang': 'With Utang',
    'customer.newThisMonth': 'New This Month',
    'customer.noCustomersFound': 'No customers found',
    'customer.adjustSearchTerms': 'Try adjusting your search terms',
    'customer.since': 'Since',
    'customer.totalUtang': 'Total Utang',
    'customer.activeUtang': 'Active Utang',
    'customer.utangRecords': 'UTANG RECORDS',
    'customer.recentTransactions': 'Recent Transactions',
    'customer.moreTransactions': 'more transactions',
    'customer.editCustomer': 'Edit Customer',
    'customer.updateCustomer': 'Update Customer',
    'customer.searchCustomers': 'Search customers by name or phone...',
    'customer.customerRequired': 'Customer name is required.',
    'customer.customerAdded': 'Customer Added',
    'customer.addedToList': 'has been added to customer list.',
    'customer.customerUpdated': 'Customer Updated',
    'customer.enterCustomerName': 'Enter customer name',
    'customer.enterPhoneNumber': 'Enter phone number',
    
    // Common
    'common.required': '*',
    'common.optional': '(Optional)',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.update': 'Update',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information'
  },
  bis: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.pos': 'POS',
    'nav.inventory': 'Inventaryo',
    'nav.utang': 'Utang',
    'nav.customers': 'Mga Kostumer',
    'nav.navigation': 'Navegasyon',
    'nav.description.dashboard': 'Kinatibuk-ang Datos ug Analytics',
    'nav.description.pos': 'Sistema sa Point of Sale',
    'nav.description.inventory': 'Pagdumala sa Stock',
    'nav.description.utang': 'Pagsubay sa Utang',
    'nav.description.customers': 'Database sa Kostumer',
    
    // Dashboard
    'dashboard.todaysSales': 'Halin Karon',
    'dashboard.totalSales': 'Kinatibuk-an',
    'dashboard.totalUtang': 'Kinatibuk-ang Utang',
    'dashboard.monthlyUtang': 'Binuwan',
    'dashboard.lowStockItems': 'Gamay nga Stock',
    'dashboard.needRestocking': 'Kinahanglan og restock',
    'dashboard.customers': 'Mga Kostumer',
    'dashboard.registeredCustomers': 'Narehistro nga kostumer',
    'dashboard.lowStockAlert': 'Alerto sa Gamay nga Stock',
    'dashboard.itemsRequiringAttention': 'Mga butang nga kinahanglan og pagtagad',
    'dashboard.allProductsWellStocked': 'Tanan nga produkto igo na ang stock! 🎉',
    'dashboard.recentUnpaidUtang': 'Bag-ong Wala Pay Bayad nga Utang',
    'dashboard.latestCreditTransactions': 'Pinakabag-ong mga transaksyon sa utang',
    'dashboard.noUnpaidUtang': 'Walay wala pa bayad nga utang! 💰',
    'dashboard.left': 'nahabilin',
    'dashboard.min': 'Min',
    
    // POS System
    'pos.products': 'Mga Produkto',
    'pos.cart': 'Cart',
    'pos.cartEmpty': 'Walay sulod ang cart',
    'pos.total': 'Kinatibuk-an',
    'pos.checkout': 'Checkout',
    'pos.paymentMethod': 'Paagi sa Bayad',
    'pos.cash': 'Cash',
    'pos.utang': 'Utang',
    'pos.partialPayment': 'Partial nga Bayad',
    'pos.customer': 'Kostumer',
    'pos.selectCustomer': 'Pilia ang kostumer',
    'pos.amountPaid': 'Kantidad nga Gibayad',
    'pos.change': 'Sukli',
    'pos.utangAmount': 'Kantidad sa Utang',
    'pos.processTransaction': 'I-proseso ang Transaksyon',
    'pos.stock': 'Stock',
    'pos.outOfStock': 'Wala nay Stock',
    'pos.outOfStockDesc': 'wala nay stock!',
    'pos.insufficientStock': 'Kulang ang Stock',
    'pos.onlyAvailable': 'Usa ra ka',
    'pos.available': 'ang available!',
    'pos.emptyCart': 'Walay Sulod ang Cart',
    'pos.emptyCartDesc': 'Ibutang una ang mga butang sa cart sa dili pa mag-transaksyon.',
    'pos.insufficientPayment': 'Kulang ang Bayad',
    'pos.insufficientPaymentDesc': 'Ang kantidad sa bayad kulang pa.',
    'pos.customerRequired': 'Kinahanglan ang Kostumer',
    'pos.customerRequiredDesc': 'Pilia ang kostumer para sa utang nga transaksyon.',
    'pos.transactionCompleted': 'Nahuman na ang Transaksyon',
    'pos.saleProcessed': 'Ang halin nga ₱{amount} na-proseso na!',
    
    // Inventory Management
    'inventory.addProduct': 'Idugang ang Produkto',
    'inventory.addNewProduct': 'Idugang ang Bag-ong Produkto',
    'inventory.productName': 'Ngalan sa Produkto',
    'inventory.category': 'Kategorya',
    'inventory.price': 'Presyo',
    'inventory.stock': 'Stock',
    'inventory.minStock': 'Minimum nga Stock',
    'inventory.barcode': 'Barcode',
    'inventory.supplier': 'Supplier',
    'inventory.cancel': 'Kanselahon',
    'inventory.edit': 'Usbon',
    'inventory.editProduct': 'Usbon ang Produkto',
    'inventory.updateProduct': 'I-update ang Produkto',
    'inventory.lowStockAlert': 'Alerto sa Gamay nga Stock',
    'inventory.items': 'ka butang',
    'inventory.searchProducts': 'Pangitaa ang mga produkto...',
    'inventory.products': 'Mga Produkto',
    'inventory.currentStock': 'Kasamtangan nga Stock',
    'inventory.noProductsFound': 'Walay produkto nga nakaplagan sa imong pagpangita.',
    'inventory.invalidInput': 'Sayop nga Input',
    'inventory.fillRequiredFields': 'Pun-i ang tanan nga kinahanglan nga mga field.',
    'inventory.productAdded': 'Naidugang na ang Produkto',
    'inventory.addedToInventory': 'naidugang na sa inventory.',
    'inventory.productUpdated': 'Na-update na ang Produkto',
    'inventory.hasBeenUpdated': 'na-update na.',
    'inventory.productDelded': 'Natangtang na ang Produkto',
    'inventory.removedFromInventory': 'natangtang na sa inventory.',
    'inventory.enterProductName': 'Ibutang ang ngalan sa produkto',
    'inventory.enterCategory': 'Ibutang ang kategorya',
    'inventory.enterBarcode': 'Ibutang ang barcode',
    'inventory.enterSupplier': 'Ibutang ang ngalan sa supplier',
    
    // Utang Management
    'utang.utangManagement': 'Pagdumala sa Utang',
    'utang.trackAndManage': 'Subayan ug dumalaon ang mga rekord sa utang sa kostumer',
    'utang.totalUnpaidUtang': 'Kinatibuk-ang Wala Pay Bayad nga Utang',
    'utang.all': 'Tanan',
    'utang.unpaid': 'Wala Pay Bayad',
    'utang.partial': 'Partial',
    'utang.paid': 'Nabayad na',
    'utang.latest': 'Pinakabag-o',
    'utang.transaction': 'transaksyon',
    'utang.transactions': 'mga transaksyon',
    'utang.allItemsPurchased': 'Tanan nga Napalit',
    'utang.item': 'BUTANG',
    'utang.qtyPrice': 'GIDAGHANON × PRESYO = TOTAL',
    'utang.totalAmount': 'Kinatibuk-ang Kantidad',
    'utang.balance': 'Balance',
    'utang.addPayment': 'Idugang ang Bayad',
    'utang.paymentHistory': 'Kasaysayan sa Bayad',
    'utang.noUtangRecords': 'Walay utang nga rekord sa napili nga filter.',
    'utang.remainingBalance': 'Nahabilin nga Balance',
    'utang.paymentAmount': 'Kantidad sa Bayad',
    'utang.note': 'Nota (Opsyonal)',
    'utang.addNoteForPayment': 'Idugang ang nota para sa bayad',
    'utang.recordPayment': 'I-rekord ang Bayad',
    'utang.invalidAmount': 'Sayop nga Kantidad',
    'utang.enterValidAmount': 'Ibutang ang sakto nga kantidad sa bayad.',
    'utang.overpayment': 'Sobra ang Bayad',
    'utang.exceedsBalance': 'Ang kantidad sa bayad sobra sa nahabilin nga balance nga P{amount}.',
    'utang.paymentRecorded': 'Na-rekord na ang Bayad',
    'utang.paymentOf': 'Ang bayad nga P{amount} na-rekord na.',
    
    // Customer Management
    'customer.addCustomer': 'Idugang ang Kostumer',
    'customer.addNewCustomer': 'Idugang ang Bag-ong Kostumer',
    'customer.customerName': 'Ngalan sa Kostumer',
    'customer.phoneNumber': 'Numero sa Telepono',
    'customer.totalCustomers': 'Kinatibuk-ang Kostumer',
    'customer.withUtang': 'Adunay Utang',
    'customer.newThisMonth': 'Bag-o Karong Buwan',
    'customer.noCustomersFound': 'Walay kostumer nga nakaplagan',
    'customer.adjustSearchTerms': 'Sulayi ang pag-usab sa imong pagpangita',
    'customer.since': 'Sukad',
    'customer.totalUtang': 'Kinatibuk-ang Utang',
    'customer.activeUtang': 'Active nga Utang',
    'customer.utangRecords': 'REKORD SA UTANG',
    'customer.recentTransactions': 'Bag-ong Mga Transaksyon',
    'customer.moreTransactions': 'pa nga mga transaksyon',
    'customer.editCustomer': 'Usbon ang Kostumer',
    'customer.updateCustomer': 'I-update ang Kostumer',
    'customer.searchCustomers': 'Pangitaa ang mga kostumer pinaagi sa ngalan o numero...',
    'customer.customerRequired': 'Kinahanglan ang ngalan sa kostumer.',
    'customer.customerAdded': 'Naidugang na ang Kostumer',
    'customer.addedToList': 'naidugang na sa lista sa kostumer.',
    'customer.customerUpdated': 'Na-update na ang Kostumer',
    'customer.enterCustomerName': 'Ibutang ang ngalan sa kostumer',
    'customer.enterPhoneNumber': 'Ibutang ang numero sa telepono',
    
    // Common
    'common.required': '*',
    'common.optional': '(Opsyonal)',
    'common.search': 'Pangita',
    'common.filter': 'Filter',
    'common.add': 'Idugang',
    'common.edit': 'Usbon',
    'common.delete': 'Tangtangon',
    'common.save': 'I-save',
    'common.cancel': 'Kanselahon',
    'common.update': 'I-update',
    'common.confirm': 'Oo',
    'common.close': 'Sirado',
    'common.loading': 'Nag-load...',
    'common.error': 'Sayop',
    'common.success': 'Sakto',
    'common.warning': 'Pasidaan',
    'common.info': 'Impormasyon'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};